# Generated by Django 3.2.22 on 2023-11-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20230620_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='name',
            new_name='Fname',
        ),
        migrations.AddField(
            model_name='data',
            name='Address',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='Lname',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='Username',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
